import Head from "next/head";
import Link from "next/link";
import { useState } from "react";

export default function Home() {
  const [toggle, setToggle] = useState(false);
  return (
    <>
      <Head>
        <title>Single Page App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav className="fixed z-20 w-full bg-white/90 shadow-2xl shadow-gray-600/5 border-b border-gray-100">
          <div className="xl:container m-auto px-6 md:px-12 lg:px-6">
            <div className="flex flex-wrap items-center justify-between gap-6 md:py-3 md:gap-0 lg:py-5">
              <div className="w-full items-center flex justify-between lg:w-auto">
                <a href="#" className="flex items-center">
                  <img
                    src="paysoko.png"
                    className="h-6 mr-3 sm:h-9"
                    alt="Paysoko Logo"
                  />
                </a>
                <label
                  htmlFor="hbr"
                  onClick={() => setToggle(!toggle)}
                  className="peer-checked:hamburger block relative z-20 p-6 -mr-6 cursor-pointer lg:hidden"
                >
                  <div
                    aria-hidden="true"
                    className="m-auto h-0.5 w-5 rounded bg-gray-900 transition duration-300"
                  ></div>
                  <div
                    aria-hidden="true"
                    className="m-auto mt-2 h-0.5 w-5 rounded bg-gray-900 transition duration-300"
                  ></div>
                </label>
              </div>
              <div
                className={`${
                  !toggle && "hidden"
                } w-full flex-wrap justify-end items-center mb-16 space-y-8 p-6 border border-gray-100 rounded-3xl shadow-2xl shadow-gray-300/20 bg-white lg:space-y-0 lg:p-0 lg:m-0 lg:flex md:flex-nowrap lg:bg-transparent lg:w-7/12 lg:shadow-none lg:border-0`}
              >
                <div className="w-full space-y-2 border-primary/10 flex flex-col -ml-1 sm:flex-row lg:space-y-0 md:w-max lg:border-l">
                  <Link
                    href="/sign-up"
                    className="relative flex h-9 md:ml-auto items-center justify-center sm:px-6"
                  >
                    <span className="relative text-sm font-semibold">
                      Sign Up
                    </span>
                  </Link>
                  <Link
                    href="/login"
                    className="relative flex h-9 md:ml-auto items-center justify-center sm:px-6"
                  >
                    <span className="relative text-sm font-semibold text-gray-900">
                      Login
                    </span>
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </nav>
      </header>

      <div className="bg-white h-screen relative pt-40 pb-20 lg:pt-44">
        <div className="relative xl:container m-auto px-6 md:px-12 lg:px-6">
          <h1 className="sm:mx-auto sm:w-10/12 md:w-2/3 font-black text-blue-900 text-4xl text-center sm:text-5xl md:text-6xl lg:w-auto lg:text-left xl:text-7xl">
            Run successful single page <br className="lg:block hidden"></br>
            <span className="relative text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-cyan-500">
              eCommerce shops
            </span>
            .
          </h1>
          <div className="lg:flex">
            <div className="relative mt-8 md:mt-16 space-y-8 sm:w-10/12 md:w-2/3 lg:ml-0 sm:mx-auto text-center lg:text-left lg:mr-auto lg:w-7/12">
              <p className="sm:text-lg text-gray-700 lg:w-11/12">
                PaySoko Payments and eBusiness solutions gives your brand access
                to modern commerce and modern digital payments solutions,
                offering your businesses new opportunities for growth and
                success.
              </p>
              <div className="mx-auto mt-8 max-w-xl bg-[#343434]/20 p-3 rounded-md">
                <form action="#" className="sm:flex sm:gap-4">
                  <div className="sm:flex-1">
                    <input
                      type="text"
                      placeholder="Enter page ID"
                      className="w-full rounded-md border-gray-200 bg-white p-3 text-gray-700 shadow-sm transition focus:border-white focus:outline-none focus:ring focus:ring-yellow-400"
                    />
                  </div>

                  <button
                    type="submit"
                    className="group mt-4 flex w-full items-center cursor-pointer justify-center gap-2 rounded-md bg-rose-600 px-5 py-3 text-white transition focus:outline-none focus:ring focus:ring-yellow-400 sm:mt-0 sm:w-auto"
                  >
                    <span className="text-sm font-medium"> Search </span>

                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      strokeWidth={1.5}
                      stroke="currentColor"
                      className="w-5 h-5"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z"
                      />
                    </svg>
                  </button>
                </form>
              </div>
            </div>
            <div className="mt-12 md:mt-0 lg:absolute -right-10 lg:w-7/12">
              <div className="relative w-full">
                <div
                  aria-hidden="true"
                  className="absolute scale-75 md:scale-110 inset-0 m-auto w-full h-full md:w-96 md:h-96 rounded-full rotate-45 bg-gradient-to-r from-red-600 to-cyan-300 blur-3xl"
                ></div>
                <img
                  src="https://tailus.io/sources/blocks/tech-startup/preview/images/globalization-cuate.svg"
                  className="relative w-full"
                  alt="wath illustration"
                  loading="lazy"
                  width="320"
                  height="280"
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
